// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: C:/Users/Ludvi/Documents/AndroidStudioProjects/PracticaCompi/app/src/main/java/com/example/decompi/compiler/lexer.flex

package com.example.decompi.compiler;

import java.util.ArrayList;
import java.util.List;
import java.util.Collections;
import java.util.Comparator;
import java_cup.runtime.*;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\10\1\0\1\11\1\12\1\0\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\12\23"+
    "\2\0\1\24\1\25\1\26\2\0\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\2\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\40\1\56\1\0\1\57"+
    "\2\0\1\60\1\0\6\61\24\40\1\0\1\62\10\0"+
    "\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\2\2\1\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\1\1\12\1\13"+
    "\1\14\1\15\1\16\16\17\1\20\1\21\1\0\1\22"+
    "\6\0\1\23\1\13\1\24\1\25\1\26\17\17\1\27"+
    "\3\17\1\30\5\0\5\17\1\31\12\17\1\32\1\17"+
    "\1\33\4\0\5\17\1\0\5\17\1\34\7\17\4\0"+
    "\1\35\4\17\2\0\1\17\1\36\1\17\1\37\5\17"+
    "\1\40\2\17\4\0\2\17\1\41\1\17\1\0\1\36"+
    "\2\17\1\42\6\17\4\0\1\43\2\17\1\0\1\17"+
    "\1\44\1\17\1\45\3\17\1\46\4\0\1\47\4\0"+
    "\1\17\1\50\1\0\1\17\1\51\3\17\2\0\1\52"+
    "\6\0\1\53\1\17\1\0\4\17\5\0\1\54\3\0"+
    "\1\55\1\0\2\17\1\56\1\17\11\0\1\57\3\17"+
    "\10\0\1\57\3\17\1\60\4\0\1\61\4\0\1\62"+
    "\2\17\4\0\1\63\4\0\1\64\2\17\1\65\2\0"+
    "\1\66\1\0\1\67\2\0\1\17\1\70\2\0\1\71"+
    "\2\0\1\17\4\0\1\17\2\0\1\72\1\0\1\17"+
    "\1\73\2\0\1\17\1\0\1\74\1\17\1\75\1\76";

  private static int [] zzUnpackAction() {
    int [] result = new int[308];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\63\0\146\0\231\0\314\0\377\0\u0132"+
    "\0\u0165\0\63\0\63\0\63\0\63\0\63\0\63\0\u0198"+
    "\0\63\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297\0\u02ca\0\u02fd"+
    "\0\u0330\0\u0363\0\u0396\0\u03c9\0\u03fc\0\u042f\0\u0462\0\u0495"+
    "\0\u04c8\0\u04fb\0\u052e\0\u0561\0\63\0\314\0\63\0\u0594"+
    "\0\u05c7\0\u05fa\0\u062d\0\u0660\0\u0693\0\63\0\u0198\0\63"+
    "\0\63\0\63\0\u06c6\0\u06f9\0\u072c\0\u075f\0\u0792\0\u07c5"+
    "\0\u07f8\0\u082b\0\u085e\0\u0891\0\u08c4\0\u08f7\0\u092a\0\u095d"+
    "\0\u0990\0\u02ca\0\u09c3\0\u09f6\0\u0a29\0\63\0\u0a5c\0\u0a8f"+
    "\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e\0\u0bc1\0\u0bf4\0\u0c27"+
    "\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26\0\u0d59\0\u0d8c\0\u0dbf"+
    "\0\u0df2\0\u0e25\0\u0e58\0\u02ca\0\u0e8b\0\63\0\u0ebe\0\u0ef1"+
    "\0\u0f24\0\u0f57\0\u0f8a\0\u0fbd\0\u0ff0\0\u1023\0\u1056\0\u1089"+
    "\0\u10bc\0\u10ef\0\u1122\0\u1155\0\u1188\0\u02ca\0\u11bb\0\u11ee"+
    "\0\u1221\0\u1254\0\u1287\0\u12ba\0\u12ed\0\u1320\0\u1353\0\u1386"+
    "\0\u13b9\0\u02ca\0\u13ec\0\u141f\0\u1452\0\u1485\0\u14b8\0\u14eb"+
    "\0\u151e\0\u02ca\0\u1551\0\u02ca\0\u1584\0\u15b7\0\u15ea\0\u161d"+
    "\0\u1650\0\u02ca\0\u1683\0\u16b6\0\u16e9\0\u171c\0\u174f\0\u1782"+
    "\0\u17b5\0\u17e8\0\u02ca\0\u181b\0\u184e\0\63\0\u1881\0\u18b4"+
    "\0\u02ca\0\u18e7\0\u191a\0\u194d\0\u1980\0\u19b3\0\u19e6\0\u1a19"+
    "\0\u1a4c\0\u1a7f\0\u1ab2\0\u02ca\0\u1ae5\0\u1b18\0\u1b4b\0\u1b7e"+
    "\0\u02ca\0\u1bb1\0\u02ca\0\u1be4\0\u1c17\0\u1c4a\0\u02ca\0\u1c7d"+
    "\0\u1cb0\0\u1ce3\0\u1d16\0\63\0\u1d49\0\u1d7c\0\u1daf\0\u1de2"+
    "\0\u1e15\0\u02ca\0\u1e48\0\u1e7b\0\u02ca\0\u1eae\0\u1ee1\0\u1f14"+
    "\0\u1f47\0\u1f7a\0\63\0\u1fad\0\u1fe0\0\u2013\0\u2046\0\u2079"+
    "\0\u20ac\0\u20df\0\u2112\0\u2145\0\u2178\0\u21ab\0\u21de\0\u2211"+
    "\0\u2244\0\u2277\0\u22aa\0\u22dd\0\u2310\0\63\0\u2343\0\u2376"+
    "\0\u23a9\0\u02ca\0\u23dc\0\u240f\0\u2442\0\u2475\0\u24a8\0\u24db"+
    "\0\u250e\0\u2541\0\u2574\0\u25a7\0\u25da\0\u260d\0\u2640\0\u2673"+
    "\0\u02ca\0\u26a6\0\u26d9\0\u270c\0\u273f\0\u2772\0\u27a5\0\u27d8"+
    "\0\u280b\0\u283e\0\u2871\0\u28a4\0\63\0\u28d7\0\u290a\0\u293d"+
    "\0\63\0\u2970\0\u29a3\0\u29d6\0\u2a09\0\63\0\u2a3c\0\u2a6f"+
    "\0\u2aa2\0\u2ad5\0\u02ca\0\u2b08\0\u2b3b\0\u2b6e\0\u2ba1\0\u2bd4"+
    "\0\u2c07\0\63\0\u2c3a\0\u2c6d\0\u2ca0\0\u2cd3\0\63\0\u2d06"+
    "\0\u2d39\0\63\0\u2d6c\0\u2d9f\0\63\0\u2dd2\0\63\0\u2e05"+
    "\0\u2e38\0\u2e6b\0\u02ca\0\u2e9e\0\u2ed1\0\63\0\u2f04\0\u2f37"+
    "\0\u2f6a\0\u2f9d\0\u2fd0\0\u3003\0\u3036\0\u3069\0\u309c\0\u30cf"+
    "\0\63\0\u3102\0\u3135\0\63\0\u3168\0\u319b\0\u31ce\0\u3201"+
    "\0\63\0\u3234\0\63\0\u02ca";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[308];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\27\1\31\1\32\1\27\1\33\1\34\1\27"+
    "\1\35\1\36\2\27\1\37\1\27\1\40\1\41\1\42"+
    "\1\27\1\43\3\27\2\2\1\27\1\44\65\0\1\3"+
    "\105\0\1\45\35\0\7\46\1\47\47\46\1\50\3\46"+
    "\2\7\1\0\2\7\1\0\55\7\11\0\1\51\17\0"+
    "\1\52\1\53\1\0\1\54\4\0\1\55\33\0\1\56"+
    "\73\0\1\57\60\0\1\57\1\0\1\22\64\0\1\60"+
    "\62\0\1\61\62\0\1\62\60\0\1\27\3\0\20\27"+
    "\1\63\7\27\1\0\2\27\24\0\1\27\3\0\30\27"+
    "\1\0\2\27\24\0\1\27\3\0\10\27\1\64\4\27"+
    "\1\65\12\27\1\0\2\27\24\0\1\27\3\0\12\27"+
    "\1\66\1\27\1\67\13\27\1\0\2\27\24\0\1\27"+
    "\3\0\10\27\1\70\17\27\1\0\2\27\24\0\1\71"+
    "\3\0\1\72\5\71\22\27\1\0\1\27\1\71\24\0"+
    "\1\27\3\0\14\27\1\73\13\27\1\0\2\27\24\0"+
    "\1\27\3\0\4\27\1\74\23\27\1\0\2\27\24\0"+
    "\1\27\3\0\10\27\1\75\4\27\1\76\12\27\1\0"+
    "\2\27\24\0\1\27\3\0\1\77\27\27\1\0\2\27"+
    "\24\0\1\27\3\0\4\27\1\100\10\27\1\101\12\27"+
    "\1\0\2\27\24\0\1\27\3\0\10\27\1\102\17\27"+
    "\1\0\2\27\24\0\1\27\3\0\10\27\1\103\17\27"+
    "\1\0\2\27\24\0\1\27\3\0\1\104\3\27\1\105"+
    "\23\27\1\0\2\27\63\0\1\106\2\46\4\0\55\46"+
    "\11\0\1\107\115\0\1\110\51\0\1\111\66\0\1\112"+
    "\56\0\1\113\52\0\1\27\3\0\10\27\1\114\17\27"+
    "\1\0\2\27\24\0\1\27\3\0\20\27\1\115\7\27"+
    "\1\0\2\27\24\0\1\27\3\0\13\27\1\116\14\27"+
    "\1\0\2\27\24\0\1\27\3\0\10\27\1\117\17\27"+
    "\1\0\2\27\24\0\1\27\3\0\22\27\1\120\5\27"+
    "\1\0\2\27\24\0\1\27\3\0\14\27\1\121\13\27"+
    "\1\0\2\27\24\0\1\122\3\0\6\122\22\27\1\0"+
    "\1\27\1\122\24\0\1\122\3\0\2\122\1\123\3\122"+
    "\22\27\1\0\1\27\1\122\24\0\1\27\3\0\10\27"+
    "\1\124\17\27\1\0\2\27\24\0\1\27\3\0\4\27"+
    "\1\125\23\27\1\0\2\27\24\0\1\27\3\0\4\27"+
    "\1\126\23\27\1\0\2\27\24\0\1\27\3\0\21\27"+
    "\1\127\6\27\1\0\2\27\24\0\1\27\3\0\20\27"+
    "\1\130\7\27\1\0\2\27\24\0\1\27\3\0\2\27"+
    "\1\131\25\27\1\0\2\27\24\0\1\27\3\0\13\27"+
    "\1\132\14\27\1\0\2\27\24\0\1\27\3\0\13\27"+
    "\1\133\14\27\1\0\2\27\24\0\1\27\3\0\20\27"+
    "\1\134\7\27\1\0\2\27\24\0\1\27\3\0\20\27"+
    "\1\135\7\27\1\0\2\27\12\0\1\136\112\0\1\137"+
    "\55\0\1\140\63\0\1\141\76\0\1\142\34\0\1\27"+
    "\3\0\1\143\27\27\1\0\2\27\24\0\1\27\3\0"+
    "\2\27\1\144\25\27\1\0\2\27\24\0\1\27\3\0"+
    "\10\27\1\145\17\27\1\0\2\27\24\0\1\27\3\0"+
    "\16\27\1\146\11\27\1\0\2\27\24\0\1\27\3\0"+
    "\15\27\1\147\12\27\1\0\2\27\2\0\2\150\1\0"+
    "\2\150\15\0\1\27\3\0\13\27\1\151\5\27\1\152"+
    "\6\27\1\0\2\27\24\0\1\153\3\0\6\153\22\27"+
    "\1\0\1\27\1\153\24\0\1\153\3\0\4\153\1\154"+
    "\1\153\22\27\1\0\1\27\1\153\24\0\1\27\3\0"+
    "\2\27\1\155\25\27\1\0\2\27\24\0\1\27\3\0"+
    "\20\27\1\156\7\27\1\0\2\27\24\0\1\27\3\0"+
    "\14\27\1\157\13\27\1\0\2\27\24\0\1\27\3\0"+
    "\22\27\1\160\5\27\1\0\2\27\24\0\1\27\3\0"+
    "\1\161\27\27\1\0\2\27\24\0\1\27\3\0\22\27"+
    "\1\162\5\27\1\0\2\27\24\0\1\27\3\0\1\27"+
    "\1\163\26\27\1\0\2\27\24\0\1\27\3\0\4\27"+
    "\1\164\23\27\1\0\2\27\24\0\1\27\3\0\3\27"+
    "\1\165\24\27\1\0\2\27\45\0\1\166\45\0\1\167"+
    "\105\0\1\170\57\0\1\171\36\0\1\27\3\0\12\27"+
    "\1\172\15\27\1\0\2\27\24\0\1\27\3\0\23\27"+
    "\1\173\4\27\1\0\2\27\24\0\1\27\3\0\2\27"+
    "\1\174\25\27\1\0\2\27\24\0\1\27\3\0\21\27"+
    "\1\175\6\27\1\0\2\27\24\0\1\27\3\0\14\27"+
    "\1\176\13\27\1\0\2\27\2\0\2\150\1\0\2\150"+
    "\34\0\1\177\5\0\1\200\35\0\1\27\3\0\10\27"+
    "\1\201\17\27\1\0\2\27\24\0\1\27\3\0\10\27"+
    "\1\202\17\27\1\0\2\27\24\0\1\203\3\0\6\203"+
    "\22\27\1\0\1\27\1\203\24\0\1\203\3\0\6\203"+
    "\12\27\1\204\7\27\1\0\1\27\1\203\24\0\1\27"+
    "\3\0\10\27\1\205\17\27\1\0\2\27\24\0\1\27"+
    "\3\0\22\27\1\206\5\27\1\0\2\27\24\0\1\27"+
    "\3\0\20\27\1\207\7\27\1\0\2\27\24\0\1\27"+
    "\3\0\12\27\1\210\15\27\1\0\2\27\24\0\1\27"+
    "\3\0\1\211\27\27\1\0\2\27\24\0\1\27\3\0"+
    "\15\27\1\212\12\27\1\0\2\27\24\0\1\27\3\0"+
    "\21\27\1\213\6\27\1\0\2\27\24\0\1\27\3\0"+
    "\1\214\27\27\1\0\2\27\50\0\1\215\65\0\1\216"+
    "\57\0\1\217\42\0\1\220\56\0\1\27\3\0\12\27"+
    "\1\221\15\27\1\0\2\27\24\0\1\27\3\0\30\27"+
    "\1\0\1\222\1\27\24\0\1\27\3\0\4\27\1\223"+
    "\23\27\1\0\2\27\24\0\1\27\3\0\2\27\1\224"+
    "\25\27\1\0\2\27\40\0\1\225\62\0\1\226\46\0"+
    "\1\27\3\0\4\27\1\227\23\27\1\0\2\27\24\0"+
    "\1\230\3\0\6\230\22\27\1\0\1\27\1\230\24\0"+
    "\1\27\3\0\15\27\1\231\12\27\1\0\2\27\24\0"+
    "\1\27\3\0\20\27\1\232\7\27\1\0\2\27\24\0"+
    "\1\27\3\0\1\233\27\27\1\0\2\27\24\0\1\27"+
    "\3\0\4\27\1\234\23\27\1\0\2\27\24\0\1\27"+
    "\3\0\14\27\1\235\13\27\1\0\2\27\24\0\1\27"+
    "\3\0\30\27\1\0\1\236\1\27\24\0\1\27\3\0"+
    "\14\27\1\237\13\27\1\0\2\27\61\0\1\240\43\0"+
    "\1\241\50\0\1\242\113\0\1\243\25\0\1\27\3\0"+
    "\15\27\1\244\12\27\1\0\2\27\24\0\1\27\3\0"+
    "\21\27\1\245\6\27\1\0\2\27\24\0\1\27\3\0"+
    "\4\27\1\246\23\27\1\0\2\27\34\0\1\247\52\0"+
    "\1\27\3\0\14\27\1\250\13\27\1\0\2\27\24\0"+
    "\1\251\3\0\6\251\22\27\1\0\1\27\1\251\24\0"+
    "\1\27\3\0\1\252\27\27\1\0\2\27\24\0\1\27"+
    "\3\0\20\27\1\253\7\27\1\0\2\27\24\0\1\27"+
    "\3\0\12\27\1\254\15\27\1\0\2\27\24\0\1\27"+
    "\3\0\6\27\1\255\21\27\1\0\2\27\24\0\1\27"+
    "\3\0\14\27\1\256\13\27\1\0\2\27\24\0\1\27"+
    "\3\0\1\257\27\27\1\0\2\27\31\0\1\260\11\0"+
    "\1\261\5\0\1\262\1\263\62\0\1\264\71\0\1\265"+
    "\32\0\1\266\11\0\1\267\5\0\1\270\35\0\1\27"+
    "\3\0\1\271\27\27\1\0\2\27\24\0\1\27\3\0"+
    "\21\27\1\272\6\27\1\0\2\27\44\0\1\273\42\0"+
    "\1\27\3\0\22\27\1\274\5\27\1\0\2\27\24\0"+
    "\1\27\3\0\21\27\1\275\6\27\1\0\2\27\24\0"+
    "\1\27\3\0\15\27\1\276\12\27\1\0\2\27\24\0"+
    "\1\27\3\0\23\27\1\277\4\27\1\0\2\27\24\0"+
    "\1\27\3\0\4\27\1\300\23\27\1\0\2\27\42\0"+
    "\1\301\60\0\1\302\62\0\1\303\56\0\1\304\57\0"+
    "\1\305\11\0\1\306\5\0\1\307\53\0\1\310\60\0"+
    "\1\311\62\0\1\312\46\0\1\27\3\0\14\27\1\313"+
    "\13\27\1\0\2\27\52\0\1\314\34\0\1\27\3\0"+
    "\20\27\1\315\7\27\1\0\2\27\24\0\1\27\3\0"+
    "\6\27\1\316\21\27\1\0\2\27\24\0\1\27\3\0"+
    "\12\27\1\317\15\27\1\0\2\27\24\0\1\27\3\0"+
    "\25\27\1\320\2\27\1\0\2\27\45\0\1\321\51\0"+
    "\1\322\104\0\1\323\46\0\1\324\60\0\1\325\62\0"+
    "\1\326\67\0\1\327\51\0\1\330\105\0\1\331\27\0"+
    "\1\27\3\0\21\27\1\332\6\27\1\0\2\27\50\0"+
    "\1\333\36\0\1\27\3\0\1\334\27\27\1\0\2\27"+
    "\24\0\1\27\3\0\20\27\1\335\7\27\1\0\2\27"+
    "\24\0\1\27\3\0\15\27\1\336\12\27\1\0\2\27"+
    "\24\0\1\27\3\0\30\27\1\0\1\337\1\27\47\0"+
    "\1\340\57\0\1\341\70\0\1\342\55\0\1\343\51\0"+
    "\1\344\75\0\1\345\57\0\1\346\52\0\1\347\56\0"+
    "\1\350\56\0\1\27\3\0\21\27\1\351\6\27\1\0"+
    "\2\27\24\0\1\27\3\0\1\352\27\27\1\0\2\27"+
    "\24\0\1\27\3\0\30\27\1\0\1\353\1\27\24\0"+
    "\1\27\3\0\20\27\1\354\7\27\1\0\2\27\53\0"+
    "\1\355\61\0\1\356\55\0\1\357\64\0\1\360\57\0"+
    "\1\361\71\0\1\362\61\0\1\363\71\0\1\364\52\0"+
    "\1\365\35\0\1\27\3\0\13\27\1\366\14\27\1\0"+
    "\2\27\24\0\1\27\3\0\20\27\1\367\7\27\1\0"+
    "\2\27\24\0\1\27\3\0\15\27\1\370\12\27\1\0"+
    "\2\27\34\0\1\371\76\0\1\372\73\0\1\373\54\0"+
    "\1\374\61\0\1\375\44\0\1\376\76\0\1\377\43\0"+
    "\1\u0100\11\0\1\u0101\5\0\1\u0102\35\0\1\27\3\0"+
    "\15\27\1\u0103\12\27\1\0\2\27\24\0\1\27\3\0"+
    "\4\27\1\u0104\23\27\1\0\2\27\24\0\1\27\3\0"+
    "\13\27\1\u0105\14\27\1\0\2\27\30\0\1\u0106\63\0"+
    "\1\u0107\11\0\1\u0108\5\0\1\u0109\45\0\1\u010a\76\0"+
    "\1\u010b\42\0\1\u010c\74\0\1\u010d\60\0\1\u010e\62\0"+
    "\1\u010f\46\0\1\27\3\0\3\27\1\u0110\24\27\1\0"+
    "\2\27\24\0\1\27\3\0\1\u0111\27\27\1\0\2\27"+
    "\51\0\1\u0112\53\0\1\u0113\60\0\1\u0114\62\0\1\u0115"+
    "\52\0\1\u0116\103\0\1\u0117\56\0\1\u0118\51\0\1\u0119"+
    "\52\0\1\27\3\0\15\27\1\u011a\12\27\1\0\2\27"+
    "\24\0\1\27\3\0\14\27\1\u011b\13\27\1\0\2\27"+
    "\45\0\1\u011c\51\0\1\u011d\77\0\1\u011e\60\0\1\u011f"+
    "\57\0\1\u0120\42\0\1\27\3\0\14\27\1\u0121\13\27"+
    "\1\0\2\27\47\0\1\u0122\57\0\1\u0123\71\0\1\u0124"+
    "\61\0\1\u0125\34\0\1\27\3\0\3\27\1\u0126\24\27"+
    "\1\0\2\27\53\0\1\u0127\61\0\1\u0128\44\0\1\u0129"+
    "\76\0\1\u012a\36\0\1\27\3\0\4\27\1\u012b\23\27"+
    "\1\0\2\27\34\0\1\u012c\76\0\1\u012d\42\0\1\u012e"+
    "\56\0\1\27\3\0\1\u012f\27\27\1\0\2\27\30\0"+
    "\1\u0130\103\0\1\u0131\35\0\1\27\3\0\3\27\1\u0132"+
    "\24\27\1\0\2\27\51\0\1\u0133\35\0\1\27\3\0"+
    "\15\27\1\u0134\12\27\1\0\2\27\1\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[12903];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\6\1\6\11\1\1\1\11\23\1\1\11"+
    "\1\0\1\11\6\0\1\11\1\1\3\11\23\1\1\11"+
    "\5\0\22\1\1\11\4\0\5\1\1\0\15\1\4\0"+
    "\5\1\2\0\14\1\4\0\4\1\1\0\1\11\11\1"+
    "\4\0\3\1\1\0\10\1\4\0\1\11\4\0\2\1"+
    "\1\0\5\1\2\0\1\11\6\0\2\1\1\0\4\1"+
    "\5\0\1\11\3\0\1\1\1\0\4\1\11\0\4\1"+
    "\10\0\1\11\3\1\1\11\4\0\1\11\4\0\3\1"+
    "\4\0\1\11\4\0\1\11\2\1\1\11\2\0\1\11"+
    "\1\0\1\11\2\0\2\1\2\0\1\11\2\0\1\1"+
    "\4\0\1\1\2\0\1\11\1\0\1\1\1\11\2\0"+
    "\1\1\1\0\1\11\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[308];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline + 1, yycolumn + 1);
    }
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { // Return error token or handle lexical error
    System.err.println("Lexical error: " + yytext() + " at line " + (yyline+1) + ", column " + (yycolumn+1));
            }
          // fall through
          case 63: break;
          case 2:
            { /* ignore */
            }
          // fall through
          case 64: break;
          case 3:
            { return symbol(sym.NOT);
            }
          // fall through
          case 65: break;
          case 4:
            { return symbol(sym.LPAREN);
            }
          // fall through
          case 66: break;
          case 5:
            { return symbol(sym.RPAREN);
            }
          // fall through
          case 67: break;
          case 6:
            { return symbol(sym.MULT);
            }
          // fall through
          case 68: break;
          case 7:
            { return symbol(sym.PLUS);
            }
          // fall through
          case 69: break;
          case 8:
            { return symbol(sym.COMMA);
            }
          // fall through
          case 70: break;
          case 9:
            { return symbol(sym.MINUS);
            }
          // fall through
          case 71: break;
          case 10:
            { return symbol(sym.DIV);
            }
          // fall through
          case 72: break;
          case 11:
            { return symbol(sym.NUMBER, Double.parseDouble(yytext()));
            }
          // fall through
          case 73: break;
          case 12:
            { return symbol(sym.LESS);
            }
          // fall through
          case 74: break;
          case 13:
            { return symbol(sym.ASSIGN);
            }
          // fall through
          case 75: break;
          case 14:
            { return symbol(sym.GREATER);
            }
          // fall through
          case 76: break;
          case 15:
            { return symbol(sym.ID, yytext());
            }
          // fall through
          case 77: break;
          case 16:
            { return symbol(sym.PIPE);
            }
          // fall through
          case 78: break;
          case 17:
            { return symbol(sym.NOT_EQUALS);
            }
          // fall through
          case 79: break;
          case 18:
            { return symbol(sym.STRING, yytext().substring(1, yytext().length()-1));
            }
          // fall through
          case 80: break;
          case 19:
            { return symbol(sym.AND);
            }
          // fall through
          case 81: break;
          case 20:
            { return symbol(sym.LESS_EQUAL);
            }
          // fall through
          case 82: break;
          case 21:
            { return symbol(sym.EQUALS);
            }
          // fall through
          case 83: break;
          case 22:
            { return symbol(sym.GREATER_EQUAL);
            }
          // fall through
          case 84: break;
          case 23:
            { return symbol(sym.SI);
            }
          // fall through
          case 85: break;
          case 24:
            { return symbol(sym.OR);
            }
          // fall through
          case 86: break;
          case 25:
            { return symbol(sym.FIN);
            }
          // fall through
          case 87: break;
          case 26:
            { return symbol(sym.VAR);
            }
          // fall through
          case 88: break;
          case 27:
            { return symbol(sym.SEPARATOR);
            }
          // fall through
          case 89: break;
          case 28:
            { return symbol(sym.LEER);
            }
          // fall through
          case 90: break;
          case 29:
            { return symbol(sym.FONT_ARIAL);
            }
          // fall through
          case 91: break;
          case 30:
            { return symbol(sym.FINSI);
            }
          // fall through
          case 92: break;
          case 31:
            { return symbol(sym.HACER);
            }
          // fall through
          case 93: break;
          case 32:
            { return symbol(sym.FIG_ROMBO);
            }
          // fall through
          case 94: break;
          case 33:
            { return symbol(sym.FIG_ELIPSE);
            }
          // fall through
          case 95: break;
          case 34:
            { return symbol(sym.INICIO);
            }
          // fall through
          case 96: break;
          case 35:
            { return symbol(sym.FIG_CIRCULO);
            }
          // fall through
          case 97: break;
          case 36:
            { return symbol(sym.HEX_COLOR, yytext());
            }
          // fall through
          case 98: break;
          case 37:
            { return symbol(sym.MOSTRAR);
            }
          // fall through
          case 99: break;
          case 38:
            { return symbol(sym.FONT_VERDANA);
            }
          // fall through
          case 100: break;
          case 39:
            { return symbol(sym.CONF_DEFAULT);
            }
          // fall through
          case 101: break;
          case 40:
            { return symbol(sym.ENTONCES);
            }
          // fall through
          case 102: break;
          case 41:
            { return symbol(sym.MIENTRAS);
            }
          // fall through
          case 103: break;
          case 42:
            { return symbol(sym.CONF_COLOR_SI);
            }
          // fall through
          case 104: break;
          case 43:
            { return symbol(sym.CONF_LETRA_SI);
            }
          // fall through
          case 105: break;
          case 44:
            { return symbol(sym.CONF_FIGURA_SI);
            }
          // fall through
          case 106: break;
          case 45:
            { return symbol(sym.FONT_COMIC_SANS);
            }
          // fall through
          case 107: break;
          case 46:
            { return symbol(sym.FIG_RECTANGULO);
            }
          // fall through
          case 108: break;
          case 47:
            { return symbol(sym.FINMIENTRAS);
            }
          // fall through
          case 109: break;
          case 48:
            { return symbol(sym.CONF_COLOR_BLOQUE);
            }
          // fall through
          case 110: break;
          case 49:
            { return symbol(sym.CONF_LETRA_BLOQUE);
            }
          // fall through
          case 111: break;
          case 50:
            { return symbol(sym.FIG_PARALELOGRAMO);
            }
          // fall through
          case 112: break;
          case 51:
            { return symbol(sym.CONF_FIGURA_BLOQUE);
            }
          // fall through
          case 113: break;
          case 52:
            { return symbol(sym.CONF_LETRA_SIZE_SI);
            }
          // fall through
          case 114: break;
          case 53:
            { return symbol(sym.CONF_COLOR_MIENTRAS);
            }
          // fall through
          case 115: break;
          case 54:
            { return symbol(sym.CONF_COLOR_TEXTO_SI);
            }
          // fall through
          case 116: break;
          case 55:
            { return symbol(sym.CONF_LETRA_MIENTRAS);
            }
          // fall through
          case 117: break;
          case 56:
            { return symbol(sym.FONT_TIMES_NEW_ROMAN);
            }
          // fall through
          case 118: break;
          case 57:
            { return symbol(sym.CONF_FIGURA_MIENTRAS);
            }
          // fall through
          case 119: break;
          case 58:
            { return symbol(sym.CONF_LETRA_SIZE_BLOQUE);
            }
          // fall through
          case 120: break;
          case 59:
            { return symbol(sym.CONF_COLOR_TEXTO_BLOQUE);
            }
          // fall through
          case 121: break;
          case 60:
            { return symbol(sym.CONF_LETRA_SIZE_MIENTRAS);
            }
          // fall through
          case 122: break;
          case 61:
            { return symbol(sym.CONF_COLOR_TEXTO_MIENTRAS);
            }
          // fall through
          case 123: break;
          case 62:
            { return symbol(sym.FIG_RECTANGULO_REDONDEADO);
            }
          // fall through
          case 124: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
