
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.decompi.compiler;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CONF_COLOR_TEXTO_SI = 33;
  public static final int MULT = 15;
  public static final int FIG_ELIPSE = 48;
  public static final int EQUALS = 18;
  public static final int FONT_TIMES_NEW_ROMAN = 55;
  public static final int SI = 3;
  public static final int MOSTRAR = 9;
  public static final int LPAREN = 27;
  public static final int GREATER = 22;
  public static final int ENTONCES = 4;
  public static final int FONT_VERDANA = 57;
  public static final int LESS = 23;
  public static final int FIN = 12;
  public static final int MINUS = 14;
  public static final int RPAREN = 28;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int CONF_LETRA_MIENTRAS = 41;
  public static final int FINMIENTRAS = 8;
  public static final int OR = 25;
  public static final int MIENTRAS = 6;
  public static final int COMMA = 29;
  public static final int SEPARATOR = 31;
  public static final int DIV = 16;
  public static final int LESS_EQUAL = 21;
  public static final int FONT_COMIC_SANS = 56;
  public static final int FIG_ROMBO = 52;
  public static final int PLUS = 13;
  public static final int ASSIGN = 17;
  public static final int ID = 61;
  public static final int CONF_LETRA_SI = 36;
  public static final int CONF_COLOR_SI = 34;
  public static final int EOF = 0;
  public static final int CONF_LETRA_SIZE_BLOQUE = 47;
  public static final int CONF_FIGURA_MIENTRAS = 40;
  public static final int CONF_FIGURA_SI = 35;
  public static final int GREATER_EQUAL = 20;
  public static final int error = 1;
  public static final int PIPE = 30;
  public static final int NUMBER = 58;
  public static final int CONF_COLOR_BLOQUE = 44;
  public static final int CONF_LETRA_SIZE_SI = 37;
  public static final int CONF_COLOR_TEXTO_BLOQUE = 43;
  public static final int CONF_COLOR_MIENTRAS = 39;
  public static final int FIG_RECTANGULO = 51;
  public static final int CONF_LETRA_BLOQUE = 46;
  public static final int FIG_RECTANGULO_REDONDEADO = 53;
  public static final int NOT_EQUALS = 19;
  public static final int FIG_CIRCULO = 49;
  public static final int LEER = 10;
  public static final int CONF_FIGURA_BLOQUE = 45;
  public static final int CONF_DEFAULT = 32;
  public static final int HACER = 7;
  public static final int CONF_COLOR_TEXTO_MIENTRAS = 38;
  public static final int STRING = 60;
  public static final int INICIO = 11;
  public static final int CONF_LETRA_SIZE_MIENTRAS = 42;
  public static final int FINSI = 5;
  public static final int FONT_ARIAL = 54;
  public static final int FIG_PARALELOGRAMO = 50;
  public static final int VAR = 2;
  public static final int HEX_COLOR = 59;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "SI",
  "ENTONCES",
  "FINSI",
  "MIENTRAS",
  "HACER",
  "FINMIENTRAS",
  "MOSTRAR",
  "LEER",
  "INICIO",
  "FIN",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "ASSIGN",
  "EQUALS",
  "NOT_EQUALS",
  "GREATER_EQUAL",
  "LESS_EQUAL",
  "GREATER",
  "LESS",
  "AND",
  "OR",
  "NOT",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "PIPE",
  "SEPARATOR",
  "CONF_DEFAULT",
  "CONF_COLOR_TEXTO_SI",
  "CONF_COLOR_SI",
  "CONF_FIGURA_SI",
  "CONF_LETRA_SI",
  "CONF_LETRA_SIZE_SI",
  "CONF_COLOR_TEXTO_MIENTRAS",
  "CONF_COLOR_MIENTRAS",
  "CONF_FIGURA_MIENTRAS",
  "CONF_LETRA_MIENTRAS",
  "CONF_LETRA_SIZE_MIENTRAS",
  "CONF_COLOR_TEXTO_BLOQUE",
  "CONF_COLOR_BLOQUE",
  "CONF_FIGURA_BLOQUE",
  "CONF_LETRA_BLOQUE",
  "CONF_LETRA_SIZE_BLOQUE",
  "FIG_ELIPSE",
  "FIG_CIRCULO",
  "FIG_PARALELOGRAMO",
  "FIG_RECTANGULO",
  "FIG_ROMBO",
  "FIG_RECTANGULO_REDONDEADO",
  "FONT_ARIAL",
  "FONT_TIMES_NEW_ROMAN",
  "FONT_COMIC_SANS",
  "FONT_VERDANA",
  "NUMBER",
  "HEX_COLOR",
  "STRING",
  "ID"
  };
}

